--
-- PostgreSQL database dump
--

-- Dumped from database version 15.3
-- Dumped by pg_dump version 15.3

-- Started on 2024-07-01 20:18:37

--
-- TOC entry 218 (class 1259 OID 16725)
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


--
-- TOC entry 217 (class 1259 OID 16724)
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 16710)
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);

--
-- TOC entry 220 (class 1259 OID 16738)
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetUserClaims" OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16737)
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16750)
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);


--
-- TOC entry 222 (class 1259 OID 16762)
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);


--
-- TOC entry 223 (class 1259 OID 16779)
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text
);


--
-- TOC entry 216 (class 1259 OID 16717)
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


--
-- TOC entry 224 (class 1259 OID 16815)
-- Name: Categoria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Categoria" (
    idcategoria integer NOT NULL,
    nombrecategoria character varying(255)
);


--
-- TOC entry 227 (class 1259 OID 16842)
-- Name: Categoria_idcategoria_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Categoria" ALTER COLUMN idcategoria ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."Categoria_idcategoria_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16820)
-- Name: Libro; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Libro" (
    idlibro integer NOT NULL,
    titulolibro character varying(255) NOT NULL,
    autorlibro character varying(255) NOT NULL,
    idcategoria integer NOT NULL,
    resumenlibro character varying(255)
);


--
-- TOC entry 228 (class 1259 OID 16843)
-- Name: Libro_idlibro_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Libro" ALTER COLUMN idlibro ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."Libro_idlibro_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16832)
-- Name: Resena; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Resena" (
    idresena integer NOT NULL,
    idlibro integer NOT NULL,
    calificacionresena integer NOT NULL,
    fecharesena date NOT NULL,
    descripcionresena character varying(256),
    aspnetuser character varying(256)
);

--
-- TOC entry 229 (class 1259 OID 16844)
-- Name: Resena_idresena_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Resena" ALTER COLUMN idresena ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."Resena_idresena_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3400 (class 0 OID 16725)
-- Dependencies: 218
-- Data for Name: AspNetRoleClaims; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3397 (class 0 OID 16710)
-- Dependencies: 215
-- Data for Name: AspNetRoles; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3402 (class 0 OID 16738)
-- Dependencies: 220
-- Data for Name: AspNetUserClaims; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3403 (class 0 OID 16750)
-- Dependencies: 221
-- Data for Name: AspNetUserLogins; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3404 (class 0 OID 16762)
-- Dependencies: 222
-- Data for Name: AspNetUserRoles; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3405 (class 0 OID 16779)
-- Dependencies: 223
-- Data for Name: AspNetUserTokens; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3398 (class 0 OID 16717)
-- Dependencies: 216
-- Data for Name: AspNetUsers; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."AspNetUsers" ("Id", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") VALUES ('de77e5d9-cdbd-446c-b703-823a4457545c', 'user1', 'USER1', 'mail@mail.com', 'MAIL@MAIL.COM', true, 'AQAAAAIAAYagAAAAEMTi67AwADv16A+pr6I1dWaltEpjtspMZrj80qeKNu0ansNqiGZP74JUJvXvU47LIQ==', 'LRENPZ5AXGDGCKQ4KO4MFRQT7ER432ZW', 'bc716eba-38a2-4c56-b3f9-5fc9acc2b374', NULL, false, false, NULL, true, 0);
INSERT INTO public."AspNetUsers" ("Id", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") VALUES ('65bb7e55-92b6-4226-8bc7-f591070b6ccd', 'user3', 'USER3', 'mail2@mail.com', 'MAIL2@MAIL.COM', false, 'AQAAAAIAAYagAAAAEJuhyhGD1E2uM8vhSUEqqw4/i4mlaMRVL4hUeriZvUW7Mm/HvJoWZ+nO18vNVw0OFw==', '4IPHXW6WLIOKFJK5G6DVK3Q2QZNHRJW4', 'cbf6db07-4ed0-48ed-8009-bbe330f66e82', NULL, false, false, NULL, true, 0);
INSERT INTO public."AspNetUsers" ("Id", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") VALUES ('ad25111f-b830-487e-9845-8a1f62ce9e86', 'user2', 'USER2', 'mail1@mail.com', 'MAIL1@MAIL.COM', false, 'AQAAAAIAAYagAAAAEMLXJjgppYyQi5K5h0GcbT1/9XwqDOF0lMtzaiDedK0g1LxGh/UBasTDWbb3KcGiOA==', 'MCYHWFCIWQLIZBOND4UFW2QCLEM6QZ3F', 'b7befc3e-50f9-4fbe-9c0c-f15cb43949dc', NULL, false, false, NULL, true, 0);
INSERT INTO public."AspNetUsers" ("Id", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") VALUES ('4190f1d6-9ba0-44d7-90f2-3f14e33340d6', 'user4', 'USER4', 'mail4@mail.com', 'MAIL4@MAIL.COM', true, 'AQAAAAIAAYagAAAAEBXYNz1zpGTedv7U32luY3HCKr5GsKzTIp0K6QVqkZLAnVCaHWfcXHsnqT5gOcUUNg==', 'LJ5NQAWDAD7523CXSBWLMPCEUNKFHJI3', '85f85198-5f67-4f57-bdae-3c22ff7067b3', NULL, false, false, NULL, true, 0);
INSERT INTO public."AspNetUsers" ("Id", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") VALUES ('aab2918a-5a01-4f4c-9322-faeced27773d', 'miemail@emial.com', 'MIEMAIL@EMIAL.COM', 'miemail@emial.com', 'MIEMAIL@EMIAL.COM', true, 'AQAAAAIAAYagAAAAEErEpy35EjzMw7F2BXdo10Daim7WC6TLhv9tnbuPJlYjnwrencJKhPFg1LxOgvqzsg==', 'CBPBIFUL3BAB5LGMMCN6N7DDNT7HFVPI', '83b344e1-234f-4a00-b836-c38aa9e7d719', NULL, false, false, NULL, true, 0);
INSERT INTO public."AspNetUsers" ("Id", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") VALUES ('67fb1c2d-aa51-4647-a45a-bd1f46f0b332', 'ela@ale.com', 'ELA@ALE.COM', 'ela@ale.com', 'ELA@ALE.COM', true, 'AQAAAAIAAYagAAAAEFp8hePzZQujSIUBh2RPnDlrnkF5CmPgD6kieCzRJnkYWm/KihmeVqenrFTA6qaS4Q==', '2XOGUJHDW7DGBL4RE5YBQT2VWZ6DEQFT', '0bb71c47-c27e-4b33-b07c-954e2159ac42', NULL, false, false, NULL, true, 0);
INSERT INTO public."AspNetUsers" ("Id", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") VALUES ('b302a2ff-3a3f-4c6c-9832-a1265b44b12a', 'mas1@mai2.com', 'MAS1@MAI2.COM', 'mas1@mai2.com', 'MAS1@MAI2.COM', true, 'AQAAAAIAAYagAAAAEGbWctLqAuhSrLsKk6v2Y6iuKJ/kWUv9uRifG9a21uABct1VDxZj0V6nOh/k/zezqg==', 'XYF2N7XRUVROYPBZHTQAWILIY6YUZ3HI', '40ed94cd-9b96-433b-9481-fbc9a1a16449', NULL, false, false, NULL, true, 0);
INSERT INTO public."AspNetUsers" ("Id", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") VALUES ('1ad43977-a467-4970-ac16-0a510f229347', '134@mail.com', '134@MAIL.COM', '134@mail.com', '134@MAIL.COM', true, 'AQAAAAIAAYagAAAAEBfGO8zXnxIO0dWqp/+vw1T+uGMe0fmWBhL+N7n1DC652vjIrcYDCIBKgdkxHFusYg==', '23BU7RAG2NNUSIUCNF2O6BIN4XJNJ5PP', 'c526fd55-21a5-4d5e-b9d7-7ef72563004e', NULL, false, false, NULL, true, 0);


--
-- TOC entry 3406 (class 0 OID 16815)
-- Dependencies: 224
-- Data for Name: Categoria; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Categoria" (idcategoria, nombrecategoria) OVERRIDING SYSTEM VALUE VALUES (5, 'Acción');
INSERT INTO public."Categoria" (idcategoria, nombrecategoria) OVERRIDING SYSTEM VALUE VALUES (6, 'Suspenso');
INSERT INTO public."Categoria" (idcategoria, nombrecategoria) OVERRIDING SYSTEM VALUE VALUES (7, 'Ciencia Ficción');


--
-- TOC entry 3407 (class 0 OID 16820)
-- Dependencies: 225
-- Data for Name: Libro; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Libro" (idlibro, titulolibro, autorlibro, idcategoria, resumenlibro) OVERRIDING SYSTEM VALUE VALUES (1, 'libro1', 'autor1', 7, NULL);


--
-- TOC entry 3408 (class 0 OID 16832)
-- Dependencies: 226
-- Data for Name: Resena; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Resena" (idresena, idlibro, calificacionresena, fecharesena, descripcionresena, aspnetuser) OVERRIDING SYSTEM VALUE VALUES (5, 1, 3, '2024-06-01', 'res1', 'miemail@emial.com');
INSERT INTO public."Resena" (idresena, idlibro, calificacionresena, fecharesena, descripcionresena, aspnetuser) OVERRIDING SYSTEM VALUE VALUES (6, 1, 3, '2024-06-01', 'es2', 'miemail@emial.com');


--
-- TOC entry 3396 (class 0 OID 16705)
-- Dependencies: 214
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20240628164328_initial', '8.0.6');


--
-- TOC entry 3417 (class 0 OID 0)
-- Dependencies: 217
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AspNetRoleClaims_Id_seq"', 1, false);


--
-- TOC entry 3418 (class 0 OID 0)
-- Dependencies: 219
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AspNetUserClaims_Id_seq"', 1, false);


--
-- TOC entry 3419 (class 0 OID 0)
-- Dependencies: 227
-- Name: Categoria_idcategoria_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Categoria_idcategoria_seq"', 7, true);


--
-- TOC entry 3420 (class 0 OID 0)
-- Dependencies: 228
-- Name: Libro_idlibro_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Libro_idlibro_seq"', 2, true);


--
-- TOC entry 3421 (class 0 OID 0)
-- Dependencies: 229
-- Name: Resena_idresena_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Resena_idresena_seq"', 6, true);


--
-- TOC entry 3241 (class 2606 OID 16819)
-- Name: Categoria Categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Categoria"
    ADD CONSTRAINT "Categoria_pkey" PRIMARY KEY (idcategoria);


--
-- TOC entry 3243 (class 2606 OID 16826)
-- Name: Libro Libro_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Libro"
    ADD CONSTRAINT "Libro_pkey" PRIMARY KEY (idlibro);


--
-- TOC entry 3228 (class 2606 OID 16731)
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- TOC entry 3220 (class 2606 OID 16716)
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- TOC entry 3231 (class 2606 OID 16744)
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- TOC entry 3234 (class 2606 OID 16756)
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- TOC entry 3237 (class 2606 OID 16768)
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- TOC entry 3239 (class 2606 OID 16785)
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- TOC entry 3224 (class 2606 OID 16723)
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- TOC entry 3218 (class 2606 OID 16709)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3245 (class 2606 OID 16836)
-- Name: Resena Resena_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Resena"
    ADD CONSTRAINT "Resena_pkey" PRIMARY KEY (idresena);


--
-- TOC entry 3222 (class 1259 OID 16796)
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- TOC entry 3226 (class 1259 OID 16791)
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- TOC entry 3229 (class 1259 OID 16793)
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- TOC entry 3232 (class 1259 OID 16794)
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- TOC entry 3235 (class 1259 OID 16795)
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- TOC entry 3221 (class 1259 OID 16792)
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- TOC entry 3225 (class 1259 OID 16797)
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- TOC entry 3246 (class 2606 OID 16732)
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 3247 (class 2606 OID 16745)
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3248 (class 2606 OID 16757)
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3249 (class 2606 OID 16769)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 3250 (class 2606 OID 16774)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3251 (class 2606 OID 16786)
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3253 (class 2606 OID 16837)
-- Name: Resena foraneaLibro; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Resena"
    ADD CONSTRAINT "foraneaLibro" FOREIGN KEY (idlibro) REFERENCES public."Libro"(idlibro);


--
-- TOC entry 3252 (class 2606 OID 16827)
-- Name: Libro foraneacategoria; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Libro"
    ADD CONSTRAINT foraneacategoria FOREIGN KEY (idcategoria) REFERENCES public."Categoria"(idcategoria);


--
-- TOC entry 3422 (class 0 OID 0)
-- Dependencies: 3252
-- Name: CONSTRAINT foraneacategoria ON "Libro"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON CONSTRAINT foraneacategoria ON public."Libro" IS 'llave foranea par categoria';


-- Completed on 2024-07-01 20:18:38

--
-- PostgreSQL database dump complete
--

